baseURL = "https://savemybonsai.com/"
title   = "Save My Bonsai"
languageCode = "en-us"
paginate = 10
[params]
  color = "green"
  description = "Fix every indoor bonsai problem—watering, pests, pruning & more."
  rss = "https://example.com/rss"
  mastodon = "https://example.com/mastodon"
  threads = "https://example.com/threads"
  bluesky = "https://example.com/bluesky"
  linkedin = "https://example.com/linkedin"
  github = "https://example.com/github"
  instagram = "https://example.com/instagram"
  twitter = "https://example.com/twitter"

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 30

[[menu.main]]
  identifier = "bonsai"
  name = "Bonsai"
  url = "/bonsai/"
  weight = 40

[[menu.main]]
  identifier = "bonsai-problems"
  name = "Bonsai Problems"
  url = "/bonsai/problems/"
  weight = 50

[params.mainSections]
  - "bonsai"
  - "care-basics"
  - "species"

theme = "hugo-paper"
